### ISSUE TITLE
(2) Undefined index: daily

### ISSUE THREAD

**Issue by Halama** [keboola/darksky-augmentation#9]
https://connection.keboola.com/admin/utils/logs?file=2017/11/25/05/2017-11-25-05-18-10-5a18ef028f9c7-exception

**Comment by ujovlado** [comment]
https://connection.keboola.com/admin/utils/logs?file=2018/01/18/09/2018-01-18-09-05-54-5a6055628c88e-exception

Looks like problem is when there's no latitude and longitude:

![screenshot_2018-01-18_10-54-59](https://user-images.githubusercontent.com/419849/35091840-0ce11524-fc3e-11e7-8a0b-563641ee5e6d.png)

It should be user error.

**Comment by odinuv** [comment]
fixed in 56d18364fa7f2154fb7ff5bcca08f20f660f0fbe
